Fix for .NET Core 3.1
RedBearSys/RedBear.LogDNA.Extensions.Logging pull request #3
Opened 2020-04-20 07:15 UTC by kostelis

FormattedLogValues are made internal and do not work anymore.

2020-09-30 13:56 UTC, siderisltd approved these changes
This is better than the other solution with getting the Microsoft classes as it's not breaking the TState when you want to log model

2020-09-30 13:58 UTC, siderisltd requested changes
Please remove the usage of Microsoft.Extensions.Logging.Externals namespace used in the solution.

2020-09-30 14:15 UTC, kostas-baltsoft commented
Where exactly? I cannot find where "Microsoft.Extensions.Logging.Externals" are used in the solution.

2020-09-30 14:24 UTC, siderisltd commented
Sorry @kostas-baltsoft @kostelis, my bad - it's using Microsoft.Extensions.Logging.Internal; which is not longer available. You can see my commit where I added the original files initially. -> https://github.com/RedBearSys/RedBear.LogDNA.Extensions.Logging/pull/5

Also in your method GetFirstValue - the field may be null so I strongly recommend you adding a null check. I've hit that while I was testing

From
var values = (object[])field.GetValue(lv);

To
var values = (object[])field?.GetValue(lv);

@cpwood can we merge his request once these changes are applied?

2022-01-14 11:14 UTC, kostelis commented
Hey guys, sorry for a late reply. I have implemented a possible null reference check.

2026-08-05 11:54 UTC, closed without merging